# Generated by Django 5.0.6 on 2024-07-30 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.item')),
            ],
            bases=('shop.item',),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='hardness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rarity',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rarity',
            name='multiplier',
            field=models.FloatField(default=1.0),
        ),
    ]
