# Generated by Django 5.0.6 on 2024-06-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('health', models.IntegerField(default=100)),
                ('damage', models.IntegerField(default=10)),
                ('defence', models.IntegerField(default=5)),
                ('gold_reward', models.IntegerField(default=0)),
            ],
        ),
    ]
