# Generated by Django 5.0.6 on 2024-07-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='exp_reward',
            field=models.IntegerField(default=0),
        ),
    ]
