# Generated by Django 5.0.6 on 2024-07-16 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_enemy_exp_reward'),
        ('character', '0002_character_attribute_points_character_exp_current_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrongEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('health', models.IntegerField(default=100)),
                ('damage', models.IntegerField(default=10)),
                ('defence', models.IntegerField(default=5)),
                ('gold_reward', models.IntegerField(default=0)),
                ('exp_reward', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ColosseumBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_data', models.TextField()),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='character.character')),
            ],
        ),
    ]
