# Generated by Django 5.0.6 on 2024-07-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_strongenemy_colosseumbattle'),
    ]

    operations = [
        migrations.AddField(
            model_name='colosseumbattle',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colosseumbattle',
            name='is_won',
            field=models.BooleanField(default=False),
        ),
    ]
