# Generated by Django 5.0.6 on 2024-06-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_hp', models.IntegerField(default=100)),
                ('current_hp', models.IntegerField(default=100)),
                ('damage', models.IntegerField(default=10)),
                ('defence', models.IntegerField(default=5)),
            ],
        ),
    ]
