# Generated by Django 5.0.6 on 2024-07-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='attribute_points',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='character',
            name='exp_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='exp_next',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
